import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { BedrockAgentRuntimeClient, RetrieveAndGenerateCommand } from "@aws-sdk/client-bedrock-agent-runtime";
import { createStudyPlan } from "@/lib/db";
import { v4 as uuidv4 } from "uuid";
import type { ApiResponse } from "@/types";

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.email) {
      return NextResponse.json<ApiResponse>(
        { success: false, message: "Not authenticated." },
        { status: 401 }
      );
    }

    const { classId, title, description } = await request.json();

    if (!classId || !title) {
      return NextResponse.json<ApiResponse>(
        { success: false, message: "classId and title are required." },
        { status: 400 }
      );
    }

    const client = new BedrockAgentRuntimeClient({
      region: process.env.AWS_REGION || "us-east-1",
      credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
        ...(process.env.AWS_SESSION_TOKEN && {
          sessionToken: process.env.AWS_SESSION_TOKEN,
        }),
      },
    });

    const knowledgeBaseId = "7PEG1WNUAY";

    // Strict prompt for creating a structured study schedule
    const prompt = `You are an expert academic advisor building a structured study plan for a student.
Context: Create a study plan titled "${title}" the following description (if any): "${description || 'General course synthesis'}".

Using ONLY the provided course syllabus and lecture materials in your knowledge base, generate a study schedule.
CRITICAL INSTRUCTIONS:
1. You MUST return ONLY a raw JSON array of objects.
2. Do NOT use markdown code blocks (e.g. no \`\`\`json).
3. Do NOT include any conversational text before or after the JSON.
4. Each object in the array represents a study task, and must have exactly these keys:
   - "title" (string: succinct milestone or topic name)
   - "type" (string: must be one of "Reading", "Assignment", "Test", "Lecture", "Review" or "Other")
   - "status" (string: must be exactly "PLANNED")

Example format:
[
  { "title": "Read Chapter 1 textbook", "type": "Reading", "status": "PLANNED" },
  { "title": "Complete Homework 1 on Vectors", "type": "Assignment", "status": "PLANNED" }
]`;

    const command = new RetrieveAndGenerateCommand({
      input: { text: prompt },
      retrieveAndGenerateConfiguration: {
        type: "KNOWLEDGE_BASE",
        knowledgeBaseConfiguration: {
          knowledgeBaseId,
          modelArn: `arn:aws:bedrock:${process.env.AWS_REGION || "us-east-1"}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0`
        }
      }
    });

    const response = await client.send(command);
    let answerText = response.output?.text || "[]";
    
    // Strip markdown blocks securely
    answerText = answerText.trim();
    if (answerText.startsWith("\`\`\`json")) answerText = answerText.substring(7);
    if (answerText.startsWith("\`\`\`")) answerText = answerText.substring(3);
    if (answerText.endsWith("\`\`\`")) answerText = answerText.substring(0, answerText.length - 3);
    answerText = answerText.trim();

    let items = [];
    try {
      items = JSON.parse(answerText);
      if (!Array.isArray(items)) {
        throw new Error("Parsed JSON is not an array");
      }
      
      // Add secure UUIDs to parsed items to match database schema Let's actually map them
      items = items.map(item => ({
        itemId: uuidv4(),
        classId,
        semester: "",
        title: item.title || "Study Milestone",
        type: item.type || "Other",
        status: "PLANNED" as const
      }));
    } catch (parseErr) {
      console.error("[Study Plan Gen Parse Error]", parseErr, "Raw Text:", answerText);
      return NextResponse.json<ApiResponse>(
        { success: false, message: "Failed to synthesize a valid study plan format from the course materials." },
        { status: 500 }
      );
    }

    const planId = uuidv4();
    await createStudyPlan({
      planId,
      classId,
      userEmail: session.user.email,
      title,
      description: description || "AI-generated course curriculum",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      items
    });

    return NextResponse.json<ApiResponse>({
      success: true,
      message: "Study Plan successfully generated by AI.",
      data: {
        planId
      },
    });
  } catch (error) {
    console.error("[Study Plan Generation Error]", error);
    return NextResponse.json<ApiResponse>(
      { success: false, message: "Failed to communicate with AWS Bedrock Knowledge Base." },
      { status: 500 }
    );
  }
}
