import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { createStudyPlan } from "@/lib/db";
import { v4 as uuidv4 } from 'uuid';
import type { ApiResponse } from "@/types";

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.email) {
      return NextResponse.json<ApiResponse>(
        { success: false, message: "Not authenticated." },
        { status: 401 }
      );
    }

    const { classId, title, description } = await request.json();

    if (!classId || !title) {
      return NextResponse.json<ApiResponse>(
        { success: false, message: "classId and title are required." },
        { status: 400 }
      );
    }

    const res = await fetch("http://localhost:8000/generate/study-plan", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ classId, timeframe: `${title} - ${description || ""}` }),
    });

    if (!res.ok) {
      throw new Error(`Python Backend Error: ${res.statusText}`);
    }

    const json = await res.json();
    if (!json.success) {
      throw new Error(json.message || "Failed to generate study plan.");
    }

    let items = json.data.studyPlan;
    if (!Array.isArray(items)) {
      items = [];
    }

    items = items.map((item: any) => ({
      itemId: uuidv4(),
      classId,
      semester: "",
      title: item.title || "Study Milestone",
      type: item.type || "Other",
      status: "PLANNED" as const
    }));

    const planId = uuidv4();
    await createStudyPlan({
      planId,
      classId,
      userEmail: session.user.email,
      title,
      description: description || "AI-generated course curriculum",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      items
    });

    return NextResponse.json<ApiResponse>({
      success: true,
      message: "Study Plan successfully generated by AI.",
      data: {
        planId
      },
    });
  } catch (error: any) {
    console.error("[Study Plan Generation Error]", error);
    return NextResponse.json<ApiResponse>(
      { success: false, message: error.message?.includes("fetch") ? "Failed to connect to the Python AI server. Please make sure the python backend is running on port 8000." : "Failed to generate study plan." },
      { status: 500 }
    );
  }
}
