import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import crypto from "crypto";

// In-memory store (starts empty per "no mock data" rule)
// Will persist during dev server runtime, resets on restart
let classRequests: any[] = [];

export async function GET(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.email) {
      return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
    }

    // Return the requests generated by this user
    const userRequests = classRequests.filter(r => r.userEmail === session.user?.email);

    return NextResponse.json({ success: true, data: userRequests });
  } catch (error) {
    console.error("[Requests GET Error]", error);
    return NextResponse.json({ success: false, message: "Internal Error" }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.email) {
      return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { courseCode, courseName, department } = body;

    if (!courseCode || !courseName || !department) {
      return NextResponse.json({ success: false, message: "Missing required fields" }, { status: 400 });
    }

    // Save strictly to in-memory array to avoid DB structural changes
    const newRequest = {
      id: crypto.randomUUID(),
      courseCode: courseCode.toUpperCase(),
      courseName,
      department,
      status: "PENDING",
      createdAt: new Date().toISOString(),
      userEmail: session.user.email,
    };

    classRequests.push(newRequest);

    return NextResponse.json({ success: true, data: newRequest });
  } catch (error) {
    console.error("[Requests POST Error]", error);
    return NextResponse.json({ success: false, message: "Internal Error" }, { status: 500 });
  }
}
