-- =============================================================
-- AI Usage Tracking Tables
-- Run this manually in the Supabase SQL Editor.
--
-- Table 1: ai_usage_summary
--   Tracks TOTAL cumulative input/output tokens per model,
--   across all contributors and all time.
--   Think of this as the "Total" sheet in your Excel workbook.
--
-- Table 2: ai_usage_daily
--   Tracks usage per model broken down by calendar day (UTC).
--   Think of this as a fresh tab per day.
--   Useful for daily budget monitoring.
--
-- Both tables use UPSERT logic via Postgres ON CONFLICT DO UPDATE
-- so each write is an atomic ADD operation (no duplicate rows).
-- =============================================================


-- 1. TOTAL SUMMARY TABLE
-- Primary key is the model name.
-- The token columns are additive accumulators.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_usage_summary (
    model_name         TEXT        PRIMARY KEY,
    total_input_tokens  BIGINT      NOT NULL DEFAULT 0,
    total_output_tokens BIGINT      NOT NULL DEFAULT 0,
    call_count          BIGINT      NOT NULL DEFAULT 0,
    last_updated        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Human-readable comment visible in the Supabase table viewer
COMMENT ON TABLE public.ai_usage_summary IS
    'Cumulative AI token usage per model across all contributors and time.';
COMMENT ON COLUMN public.ai_usage_summary.model_name         IS 'Gemini model identifier, e.g. gemini-3-flash-preview';
COMMENT ON COLUMN public.ai_usage_summary.total_input_tokens  IS 'Running total of all prompt/input tokens consumed by this model';
COMMENT ON COLUMN public.ai_usage_summary.total_output_tokens IS 'Running total of all candidate/output tokens generated by this model';
COMMENT ON COLUMN public.ai_usage_summary.call_count          IS 'Total number of API calls registered for this model';


-- 2. DAILY BREAKDOWN TABLE
-- Composite PK: (usage_date, model_name) — one row per model per day.
-- Token columns reset each day automatically because new dates
-- produce new rows; old rows are never mutated across day boundaries.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_usage_daily (
    usage_date         DATE        NOT NULL DEFAULT CURRENT_DATE,
    model_name         TEXT        NOT NULL,
    input_tokens       BIGINT      NOT NULL DEFAULT 0,
    output_tokens      BIGINT      NOT NULL DEFAULT 0,
    call_count         BIGINT      NOT NULL DEFAULT 0,
    last_updated       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (usage_date, model_name)
);

COMMENT ON TABLE public.ai_usage_daily IS
    'Per-day AI token usage per model. A new row is auto-created each day.';
COMMENT ON COLUMN public.ai_usage_daily.usage_date    IS 'Calendar date (UTC) the tokens were consumed';
COMMENT ON COLUMN public.ai_usage_daily.model_name   IS 'Gemini model identifier';
COMMENT ON COLUMN public.ai_usage_daily.input_tokens  IS 'Total input tokens consumed on this day for this model';
COMMENT ON COLUMN public.ai_usage_daily.output_tokens IS 'Total output tokens generated on this day for this model';
COMMENT ON COLUMN public.ai_usage_daily.call_count    IS 'Total API calls made on this day for this model';


-- 3. ROW LEVEL SECURITY
-- These are internal analytics tables.
-- Only the service role key (used by the Python backend) is allowed
-- to write. The anon/authenticated roles are read-only.
-- ------------------------------------------------------------
ALTER TABLE public.ai_usage_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_usage_daily   ENABLE ROW LEVEL SECURITY;

-- Allow service_role full access (Python backend)
CREATE POLICY "service_role_all_summary" ON public.ai_usage_summary
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "service_role_all_daily" ON public.ai_usage_daily
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow authenticated users read-only access (future admin dashboard)
CREATE POLICY "authenticated_read_summary" ON public.ai_usage_summary
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "authenticated_read_daily" ON public.ai_usage_daily
    FOR SELECT
    TO authenticated
    USING (true);


-- 4. INDEX for fast date-range queries on the daily table
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_ai_usage_daily_date
    ON public.ai_usage_daily (usage_date DESC);

CREATE INDEX IF NOT EXISTS idx_ai_usage_daily_model
    ON public.ai_usage_daily (model_name);
